spring:
  datasource:
    url: jdbc:mariadb://192.168.1.121:3306/auth
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      default-client: client1
      default-secret: secret
      iss: common-issuer
